### ISSUE TITLE
Problème augmentation de font depuis Typertools/TypeR

### ISSUE THREAD

**Issue by alt3act** [SeanR-ScanR/TypeR#1]
Lorsque la fonctionnalité d'augmentation de la taille de font de Typertools/TypeR est utilisé, celle-ci change la méthode de lissage en Légère, passant de :
<img width="227" alt="image" src="https://github.com/SeanR-ScanR/TypeR/assets/58007529/694d3ae4-24ce-41fe-8420-d066ef23b0ec">
à : 
<img width="228" alt="image" src="https://github.com/SeanR-ScanR/TypeR/assets/58007529/6ec7becb-c18c-4108-8e79-4db34416479e">

**Comment by SeanR-ScanR** [comment]
Issue fixed !
