### ISSUE TITLE
Pouvoir donner le même nom a 2 préréglages différents 

### ISSUE THREAD

**Issue by Dadaam** [SeanR-ScanR/TypeR#10]
Tout simplement parce que TT le refuse et que ça en devient chiant (pour une même font dialogue de deux séries c'est plus pratique je trouve)

**Comment by SeanR-ScanR** [comment]
Sur 2 dossiers différents je présume ? Pcq sinon c'est normal imo

**Comment by Dadaam** [comment]
> Sur 2 dossiers différents je présume ? Pcq sinon c'est normal imo

Oui c'est ça en gros

**Comment by SeanR-ScanR** [comment]
ça marche déjà par défaut, je ferme l'issue, je pense que t'es bourré Dadam
