### ISSUE TITLE
Quand tu changes la taille avec TypeR 

### ISSUE THREAD

**Issue by ImSakushi** [SeanR-ScanR/TypeR#17]
Quand tu changes la taille des textes avec TypeR ça change aussi l'interligne en conséquence si l'interligne n'est pas auto
(si taille +1 alors interligne +1)

**Comment by SeanR-ScanR** [comment]
[Merge pull request](https://github.com/SeanR-ScanR/TypeR/commit/14ba54c7b0791ad005216110205f40a8566b2e96) https://github.com/SeanR-ScanR/TypeR/pull/18 [from SeanR-ScanR/dev-issue-17](https://github.com/SeanR-ScanR/TypeR/commit/14ba54c7b0791ad005216110205f40a8566b2e96)
