### ISSUE TITLE
Modif de font après coup

### ISSUE THREAD

**Issue by Dadaam** [SeanR-ScanR/TypeR#2]
En gros, sur TT, **avant** de poser le texte a l'aide de l'outil sélection (super chiant waouh) et du raccourci ctrl+win, **on peut sélectionner la font voulue dans les styles prédéfinis de TT** que l'on a importé nous même. Néanmoins, **après** l'avoir posé et collé, **il est impossible de changer** depuis TT (qui modifie dès lors le style du texte suivant) et on doit le faire manuellement dans l'outil texte de photoshop.

Ajouter une fonctionnalité permettant de continuer d'utiliser les styles de TT après avoir collé le texte serait grandement appréciable, peut être avec un fonctionnement usant les calques (pour les erreurs d'inattention par exemple)

PS: Néanmoins je comprends au fur et a mesure que j'écris ces lignes que ça devienne potentiellement un bordel (entre les styles des anciens et nouveaux textes) donc bon...

**Comment by Skytowz** [comment]
Déjà possible dans TyperTools
