### ISSUE TITLE
Pouvoir mettre les tailles de texte avec des virgules

### ISSUE THREAD

**Issue by ImSakushi** [SeanR-ScanR/TypeR#24]
genre 24,5px pour un préreglage,
actuellement TypeR refuse les virgules.

**Comment by SeanR-ScanR** [comment]
Close in [Merge pull request](https://github.com/SeanR-ScanR/TypeR/commit/7a1d26a0c9f42e1487b6905e9068676f7909e325) https://github.com/SeanR-ScanR/TypeR/pull/25 [from SeanR-ScanR/issue-24](https://github.com/SeanR-ScanR/TypeR/commit/7a1d26a0c9f42e1487b6905e9068676f7909e325)
