### ISSUE TITLE
Faire en sorte que le texte ne change pas de forme quand on recentre (primordial imo)

### ISSUE THREAD

**Issue by ImSakushi** [SeanR-ScanR/TypeR#4]
Contrairement à Typesetterer qui se contente d'uniquement centre le texte, TyperTools réadapte aussi la forme du texte à la forme de la bulle, ce qui casse tout. 

Quand ce sera patché, TypeR sera peak 

![11](https://github.com/SeanR-ScanR/TypeR/assets/116188905/e22afb0a-6bda-4c18-9e13-3f5796f61ce7)

**Comment by SeanR-ScanR** [comment]
DONE
