### ISSUE TITLE
Pouvoir rendre la fenêtre encore plus petite

### ISSUE THREAD

**Issue by ImSakushi** [SeanR-ScanR/TypeR#7]
On ne peut pas rendre la fenêtre de TyperTools plus petite que ça (et je trouve ça trop grand), loin du minimalisme de Typesetterer
Un patch serait parfait !

![image](https://github.com/SeanR-ScanR/TypeR/assets/116188905/568ab9cd-ec01-4bff-88f3-f01b4506bb1a)
![image](https://github.com/SeanR-ScanR/TypeR/assets/116188905/d50cf6b6-ead5-4485-8567-98ec0c9becda)

**Comment by SeanR-ScanR** [comment]
Vu le nombre d'info de typer tools je suis pas trop sûr de la possibilité, après tu peux le bloquer au dessus de la vu de calque de ce que j'ai vu et ça fait gagner de la place, je vais voir pour réduire la largeur par contre c'est une possibilité
